# Generated by Django 4.0.2 on 2022-10-10 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_post_author_alter_post_quote_profilepic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='user',
            new_name='Users',
        ),
    ]
