# Generated by Django 4.0.2 on 2022-10-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_profilepic_users_profilepic_uers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='uers',
            new_name='users',
        ),
    ]
