# Generated by Django 4.0.2 on 2022-10-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_rename_uers_profilepic_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='users',
            new_name='post',
        ),
    ]
