# Generated by Django 4.0.2 on 2022-10-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_rename_users_profilepic_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilepic',
            old_name='post',
            new_name='users',
        ),
    ]
