# Generated by Django 4.0.2 on 2022-10-10 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_rename_users_profilepic_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profilepic',
        ),
    ]
