# Generated by Django 4.0.2 on 2022-10-10 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
