# Generated by Django 4.0.2 on 2022-10-10 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='profilemodel',
            new_name='profile',
        ),
    ]
